spring:
  profiles:
    active: ${profile}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  messages:
    basename: messages
    encoding: UTF-8
springdoc:
  swagger-ui:
    path: /
    operations-sorter: method
    display-request-duration: true
    tags-sorter: alpha
