name: PR 리뷰 봇

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: AWS Bedrock Code Review Action
        uses: eple0329/AWSBedrock-CodeReview@v1.1.2
        with:
          aws-access-key-id: ${{ secrets.REVIEW_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.REVIEW_AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          model: 'amazon.titan-text-premier-v1:0'
          max-tokens: 3000
          language: 'Korean'
          title: '리뷰해드려요~'
          home-directory: 'src/main/java/com/cozymate/cozymate_server''

